services:
  - type: web
    name: health-chatbot-backend
    env: python
    plan: free
    buildCommand: |
      export CARGO_HOME=/tmp/cargo
      export CARGO_TARGET_DIR=/tmp/target
      pip install --upgrade pip
      pip install --only-binary=tokenizers -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 10000
      - key: ENABLE_ML_MODELS
        value: false
      - key: PYTHON_VERSION
        value: 3.11
      - key: CARGO_HOME
        value: /tmp/cargo
      - key: CARGO_TARGET_DIR
        value: /tmp/target
    healthCheckPath: /health