services:
  - type: web
    name: health-chatbot-backend
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements-minimal.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 10000
      - key: ENABLE_ML_MODELS
        value: false
      - key: PYTHON_VERSION
        value: 3.11
      - key: DEBUG
        value: false
      - key: PIP_NO_BUILD_ISOLATION
        value: false
      - key: PIP_NO_DEPENDENCIES
        value: false
    healthCheckPath: /health